### PR TITLE
Security and convenience enhancements

### PR DESCRIPTION
**Pull request by ttulka**
I have created this branch to implement some security and convenience features we need for our project. 

- **Trim of the properties**
  As an admin it's easy to overlook an unnecessary space after a port number which caused an error.
```
# this is okay now
server.listener.port= 50983 
```

- **Property `server.globalChain` doesn't need to be set**
  When the value is empty it's confusing.
```
# this is okay now
#server.globalChain=
```

- **Listener host**
  This security feature is very important for us. When running as an integration proxy the listener musn't accept client connections from outside the localhost
```
server.listener.host=localhost

## with (listening only on localhost)
# netstat -an | grep 50983
#   TCP    127.0.0.1:50983        0.0.0.0:0              LISTENING

## without (listening on all network intefaces)
# netstat -an | grep 50983
#   TCP    0.0.0.0:50983          0.0.0.0:0              LISTENING
#   TCP    [::]:50983             [::]:0                 LISTENING
```

- **Required bind authorization**
  The bind to the MyVD worked with empty credentials (Anonymous) and there was no way how to force the user to authorizate himself by binding.
```
server.listener.authRequired=true

# An attempt to bind anonymously leads to the response:
# AUTH_METHOD_NOT_SUPPORTED: Anonymous is not a supported mechanism.
``` 

----------------------

*Implementation notes:*

- I created tests for the new features.
- I updated the documentation.
- There are no breaking changes, only additional extensions.
- I did all the changes to the `src`, the folder `server/src` remains untouched.

### CODE REVIEW

**Comment by mlbiam** [comment]
Can we break this up in to multiple pull requests.  I'm OK with merging everything except "Easy setting of the root base for integration of different namespaces"  I'm not sure I understand the use case here.  If you dno't have a common namespace, why not use the DN mapping inserts to build one rather then add a new feature?  I'm concerned that this could have un-intended consequences and be difficult to maintain.

**Comment by ttulka** [comment]
Hi, thanks for the quick reaction!

I'm definitely okay with the multiple merges. How should I do it?

The intention behind is described in the issue #43
The problem with namespaces mapping is, I can't work with the original name. For example, when I do authorization first I search for a user with username xy, then for a group with the property member=userDn. If the userDn is mapped, the query doesn't work anymore. 
This rootBase property is a shortcut to tell MyVD to search everywhere when that base is used. Has no impact if the property is not set.

**Comment by ttulka** [comment]
I have removed the last feature (`server.rootBase`) from the pull request.
Please let me know if I can do something else for the enhancements to be merged.
Thank you!

**Comment by mlbiam** [comment]
These are great features, sorry it took me a while to merge them.  looked like they were merged against 1.0.3.  We're on 1.0.4 and i'm doing a minor build for 1.0.5 with new libraries so lets plan on integrating this for 1.0.6.  So once I cut 1.0.5 I'll merge it back into master.  Can you then pull the latest and lets make sure everything still merges?

Thanks

**Comment by mlbiam** [comment]
what is `noMapBindFlag` for?  I see it in the LDAP insert

**Comment by ttulka** [comment]
I added the tests, please let me know if it's okay

**Comment by ttulka** [comment]
There is already a "success" test, all the other tests have only different credentials, so it should be sufficient from the API point. Wouldn't it be too implementation-coupled?

**Comment by ttulka** [comment]
I can put this code in the tests:
```
} catch (LDAPException e) {
    if (e.getResultCode() != 49) {
       // ???
    }}
```
But what it the error code is different from 49? Does it mean the test was successful? It sounds strange to me...

**Comment by ttulka** [comment]
Thinking about it deeper, it makes probably sence... I will commit it

**Comment by mlbiam** [comment]
> But what it the error code is different from 49? Does it mean the test was successful? It sounds strange to me...

The opposite, we want to make sure the error code is 49 since thats invalid credentials and thats what ldap clients will expect.  Any other error should be a failed test.

**Pull request merged**
